//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMASServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exception.sharedws")]
    public partial class WSException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.omaswebws")]
    public partial class TimeZone
    {
        
        private string dstLongNameField;
        
        private string dstShortNameField;
        
        private string gmtOffsetField;
        
        private string nameField;
        
        private string stdLongNameField;
        
        private string stdShortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string dstLongName
        {
            get
            {
                return this.dstLongNameField;
            }
            set
            {
                this.dstLongNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string dstShortName
        {
            get
            {
                return this.dstShortNameField;
            }
            set
            {
                this.dstShortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string gmtOffset
        {
            get
            {
                return this.gmtOffsetField;
            }
            set
            {
                this.gmtOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string stdLongName
        {
            get
            {
                return this.stdLongNameField;
            }
            set
            {
                this.stdLongNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string stdShortName
        {
            get
            {
                return this.stdShortNameField;
            }
            set
            {
                this.stdShortNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://websvcs.omaswebws", ConfigurationName="OMASServiceReference.OMASWebSvcs")]
    public interface OMASWebSvcs
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.getTimeZonesResponse> getTimeZonesAsync(OMASServiceReference.getTimeZonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.getUsersResponse> getUsersAsync(OMASServiceReference.getUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.deleteUserResponse> deleteUserAsync(OMASServiceReference.deleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.editUserResponse> editUserAsync(OMASServiceReference.editUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.createUserResponse> createUserAsync(OMASServiceReference.createUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.checkAuthorizationResponse> checkAuthorizationAsync(OMASServiceReference.checkAuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.getCompanyDetailsResponse> getCompanyDetailsAsync(OMASServiceReference.getCompanyDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.getRolesResponse> getRolesAsync(OMASServiceReference.getRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.createRoleResponse> createRoleAsync(OMASServiceReference.createRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.setUserPasswordResponse> setUserPasswordAsync(OMASServiceReference.setUserPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.getUserCapabilitiesResponse> getUserCapabilitiesAsync(OMASServiceReference.getUserCapabilitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.editRoleResponse> editRoleAsync(OMASServiceReference.editRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.deleteRoleResponse> deleteRoleAsync(OMASServiceReference.deleteRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.unlockUserResponse> unlockUserAsync(OMASServiceReference.unlockUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.renameRoleResponse> renameRoleAsync(OMASServiceReference.renameRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.getRoleDetailsResponse> getRoleDetailsAsync(OMASServiceReference.getRoleDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMASServiceReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OMASServiceReference.setUserDepotResponse> setUserDepotAsync(OMASServiceReference.setUserDepotRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimeZones", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getTimeZonesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string locale;
        
        public getTimeZonesRequest()
        {
        }
        
        public getTimeZonesRequest(string companyId, string locale)
        {
            this.companyId = companyId;
            this.locale = locale;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimeZonesResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getTimeZonesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OMASServiceReference.TimeZone[] getTimeZonesReturn;
        
        public getTimeZonesResponse()
        {
        }
        
        public getTimeZonesResponse(OMASServiceReference.TimeZone[] getTimeZonesReturn)
        {
            this.getTimeZonesReturn = getTimeZonesReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.omaswebws")]
    public partial class User
    {
        
        private string companyIdField;
        
        private string emailField;
        
        private string firstNameField;
        
        private bool forcePwdResetField;
        
        private string idField;
        
        private string lastNameField;
        
        private bool lockedOutField;
        
        private bool obeyDstField;
        
        private string pagerEmailField;
        
        private string qspInstanceField;
        
        private Role roleField;
        
        private TimeZone timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string companyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool forcePwdReset
        {
            get
            {
                return this.forcePwdResetField;
            }
            set
            {
                this.forcePwdResetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool lockedOut
        {
            get
            {
                return this.lockedOutField;
            }
            set
            {
                this.lockedOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool obeyDst
        {
            get
            {
                return this.obeyDstField;
            }
            set
            {
                this.obeyDstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string pagerEmail
        {
            get
            {
                return this.pagerEmailField;
            }
            set
            {
                this.pagerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string qspInstance
        {
            get
            {
                return this.qspInstanceField;
            }
            set
            {
                this.qspInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public Role role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public TimeZone timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.omaswebws")]
    public partial class Role
    {
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsers", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string entityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string entityType;
        
        public getUsersRequest()
        {
        }
        
        public getUsersRequest(string companyId, string entityId, string entityType)
        {
            this.companyId = companyId;
            this.entityId = entityId;
            this.entityType = entityType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OMASServiceReference.User[] getUsersReturn;
        
        public getUsersResponse()
        {
        }
        
        public getUsersResponse(OMASServiceReference.User[] getUsersReturn)
        {
            this.getUsersReturn = getUsersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUser", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class deleteUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userId;
        
        public deleteUserRequest()
        {
        }
        
        public deleteUserRequest(string companyId, string userId)
        {
            this.companyId = companyId;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUserResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class deleteUserResponse
    {
        
        public deleteUserResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editUser", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class editUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OMASServiceReference.User user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        public editUserRequest()
        {
        }
        
        public editUserRequest(OMASServiceReference.User user, string password)
        {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editUserResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class editUserResponse
    {
        
        public editUserResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUser", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class createUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OMASServiceReference.User user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        public createUserRequest()
        {
        }
        
        public createUserRequest(OMASServiceReference.User user, string password)
        {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUserResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class createUserResponse
    {
        
        public createUserResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAuthorization", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class checkAuthorizationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string applicationId;
        
        public checkAuthorizationRequest()
        {
        }
        
        public checkAuthorizationRequest(string applicationId)
        {
            this.applicationId = applicationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAuthorizationResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class checkAuthorizationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string checkAuthorizationReturn;
        
        public checkAuthorizationResponse()
        {
        }
        
        public checkAuthorizationResponse(string checkAuthorizationReturn)
        {
            this.checkAuthorizationReturn = checkAuthorizationReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.omaswebws")]
    public partial class Company
    {
        
        private string addressField;
        
        private string address2Field;
        
        private int alertRetentionField;
        
        private string cityField;
        
        private string countryField;
        
        private string custAcctNoField;
        
        private string custAuxAcctNoField;
        
        private string hubIdField;
        
        private string idField;
        
        private bool lockedOutField;
        
        private string nameField;
        
        private bool obeyDstField;
        
        private string ownAcctNoField;
        
        private string ownAuxAcctNoField;
        
        private string postalCodeField;
        
        private string qspInstanceField;
        
        private int reportRetentionField;
        
        private string stateField;
        
        private string tempUomField;
        
        private TimeZone timeZoneField;
        
        private string timeZonesObservedField;
        
        private string uomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int alertRetention
        {
            get
            {
                return this.alertRetentionField;
            }
            set
            {
                this.alertRetentionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string custAcctNo
        {
            get
            {
                return this.custAcctNoField;
            }
            set
            {
                this.custAcctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string custAuxAcctNo
        {
            get
            {
                return this.custAuxAcctNoField;
            }
            set
            {
                this.custAuxAcctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string hubId
        {
            get
            {
                return this.hubIdField;
            }
            set
            {
                this.hubIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool lockedOut
        {
            get
            {
                return this.lockedOutField;
            }
            set
            {
                this.lockedOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool obeyDst
        {
            get
            {
                return this.obeyDstField;
            }
            set
            {
                this.obeyDstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string ownAcctNo
        {
            get
            {
                return this.ownAcctNoField;
            }
            set
            {
                this.ownAcctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string ownAuxAcctNo
        {
            get
            {
                return this.ownAuxAcctNoField;
            }
            set
            {
                this.ownAuxAcctNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string qspInstance
        {
            get
            {
                return this.qspInstanceField;
            }
            set
            {
                this.qspInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int reportRetention
        {
            get
            {
                return this.reportRetentionField;
            }
            set
            {
                this.reportRetentionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string tempUom
        {
            get
            {
                return this.tempUomField;
            }
            set
            {
                this.tempUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public TimeZone timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string timeZonesObserved
        {
            get
            {
                return this.timeZonesObservedField;
            }
            set
            {
                this.timeZonesObservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompanyDetails", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getCompanyDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        public getCompanyDetailsRequest()
        {
        }
        
        public getCompanyDetailsRequest(string companyId)
        {
            this.companyId = companyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompanyDetailsResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getCompanyDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OMASServiceReference.Company getCompanyDetailsReturn;
        
        public getCompanyDetailsResponse()
        {
        }
        
        public getCompanyDetailsResponse(OMASServiceReference.Company getCompanyDetailsReturn)
        {
            this.getCompanyDetailsReturn = getCompanyDetailsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoles", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getRolesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        public getRolesRequest()
        {
        }
        
        public getRolesRequest(string companyId)
        {
            this.companyId = companyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRolesResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getRolesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OMASServiceReference.Role[] getRolesReturn;
        
        public getRolesResponse()
        {
        }
        
        public getRolesResponse(OMASServiceReference.Role[] getRolesReturn)
        {
            this.getRolesReturn = getRolesReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.omaswebws")]
    public partial class RoleDetails
    {
        
        private string nameField;
        
        private string descriptionField;
        
        private Capability[] capabilitiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Capability[] capabilities
        {
            get
            {
                return this.capabilitiesField;
            }
            set
            {
                this.capabilitiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.omaswebws")]
    public partial class Capability
    {
        
        private string applicationIdField;
        
        private string descriptionField;
        
        private string groupField;
        
        private string idField;
        
        private string positionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string applicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createRole", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class createRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OMASServiceReference.RoleDetails role;
        
        public createRoleRequest()
        {
        }
        
        public createRoleRequest(string companyId, OMASServiceReference.RoleDetails role)
        {
            this.companyId = companyId;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createRoleResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class createRoleResponse
    {
        
        public createRoleResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setUserPassword", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class setUserPasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool forcePwdReset;
        
        public setUserPasswordRequest()
        {
        }
        
        public setUserPasswordRequest(string companyId, string userId, string password, bool forcePwdReset)
        {
            this.companyId = companyId;
            this.userId = userId;
            this.password = password;
            this.forcePwdReset = forcePwdReset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setUserPasswordResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class setUserPasswordResponse
    {
        
        public setUserPasswordResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserCapabilities", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getUserCapabilitiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string applicationId;
        
        public getUserCapabilitiesRequest()
        {
        }
        
        public getUserCapabilitiesRequest(string companyId, string userId, string applicationId)
        {
            this.companyId = companyId;
            this.userId = userId;
            this.applicationId = applicationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserCapabilitiesResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getUserCapabilitiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OMASServiceReference.Capability[] getUserCapabilitiesReturn;
        
        public getUserCapabilitiesResponse()
        {
        }
        
        public getUserCapabilitiesResponse(OMASServiceReference.Capability[] getUserCapabilitiesReturn)
        {
            this.getUserCapabilitiesReturn = getUserCapabilitiesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editRole", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class editRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OMASServiceReference.RoleDetails role;
        
        public editRoleRequest()
        {
        }
        
        public editRoleRequest(string companyId, OMASServiceReference.RoleDetails role)
        {
            this.companyId = companyId;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editRoleResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class editRoleResponse
    {
        
        public editRoleResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRole", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class deleteRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string roleName;
        
        public deleteRoleRequest()
        {
        }
        
        public deleteRoleRequest(string companyId, string roleName)
        {
            this.companyId = companyId;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRoleResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class deleteRoleResponse
    {
        
        public deleteRoleResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unlockUser", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class unlockUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userId;
        
        public unlockUserRequest()
        {
        }
        
        public unlockUserRequest(string companyId, string userId)
        {
            this.companyId = companyId;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unlockUserResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class unlockUserResponse
    {
        
        public unlockUserResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="renameRole", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class renameRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string roleName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string newRoleName;
        
        public renameRoleRequest()
        {
        }
        
        public renameRoleRequest(string companyId, string roleName, string newRoleName)
        {
            this.companyId = companyId;
            this.roleName = roleName;
            this.newRoleName = newRoleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="renameRoleResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class renameRoleResponse
    {
        
        public renameRoleResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoleDetails", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getRoleDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string roleName;
        
        public getRoleDetailsRequest()
        {
        }
        
        public getRoleDetailsRequest(string companyId, string roleName)
        {
            this.companyId = companyId;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoleDetailsResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class getRoleDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OMASServiceReference.RoleDetails getRoleDetailsReturn;
        
        public getRoleDetailsResponse()
        {
        }
        
        public getRoleDetailsResponse(OMASServiceReference.RoleDetails getRoleDetailsReturn)
        {
            this.getRoleDetailsReturn = getRoleDetailsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setUserDepot", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class setUserDepotRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.omaswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int depotId;
        
        public setUserDepotRequest()
        {
        }
        
        public setUserDepotRequest(string companyId, string userId, int depotId)
        {
            this.companyId = companyId;
            this.userId = userId;
            this.depotId = depotId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setUserDepotResponse", WrapperNamespace="http://websvcs.omaswebws", IsWrapped=true)]
    public partial class setUserDepotResponse
    {
        
        public setUserDepotResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface OMASWebSvcsChannel : OMASServiceReference.OMASWebSvcs, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class OMASWebSvcsClient : System.ServiceModel.ClientBase<OMASServiceReference.OMASWebSvcs>, OMASServiceReference.OMASWebSvcs
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OMASWebSvcsClient() : 
                base(OMASWebSvcsClient.GetDefaultBinding(), OMASWebSvcsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OMASWebSvcs.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OMASWebSvcsClient(EndpointConfiguration endpointConfiguration) : 
                base(OMASWebSvcsClient.GetBindingForEndpoint(endpointConfiguration), OMASWebSvcsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OMASWebSvcsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OMASWebSvcsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OMASWebSvcsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OMASWebSvcsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OMASWebSvcsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.getTimeZonesResponse> getTimeZonesAsync(OMASServiceReference.getTimeZonesRequest request)
        {
            return base.Channel.getTimeZonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.getUsersResponse> getUsersAsync(OMASServiceReference.getUsersRequest request)
        {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.deleteUserResponse> deleteUserAsync(OMASServiceReference.deleteUserRequest request)
        {
            return base.Channel.deleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.editUserResponse> editUserAsync(OMASServiceReference.editUserRequest request)
        {
            return base.Channel.editUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.createUserResponse> createUserAsync(OMASServiceReference.createUserRequest request)
        {
            return base.Channel.createUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.checkAuthorizationResponse> checkAuthorizationAsync(OMASServiceReference.checkAuthorizationRequest request)
        {
            return base.Channel.checkAuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.getCompanyDetailsResponse> getCompanyDetailsAsync(OMASServiceReference.getCompanyDetailsRequest request)
        {
            return base.Channel.getCompanyDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.getRolesResponse> getRolesAsync(OMASServiceReference.getRolesRequest request)
        {
            return base.Channel.getRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.createRoleResponse> createRoleAsync(OMASServiceReference.createRoleRequest request)
        {
            return base.Channel.createRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.setUserPasswordResponse> setUserPasswordAsync(OMASServiceReference.setUserPasswordRequest request)
        {
            return base.Channel.setUserPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.getUserCapabilitiesResponse> getUserCapabilitiesAsync(OMASServiceReference.getUserCapabilitiesRequest request)
        {
            return base.Channel.getUserCapabilitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.editRoleResponse> editRoleAsync(OMASServiceReference.editRoleRequest request)
        {
            return base.Channel.editRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.deleteRoleResponse> deleteRoleAsync(OMASServiceReference.deleteRoleRequest request)
        {
            return base.Channel.deleteRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.unlockUserResponse> unlockUserAsync(OMASServiceReference.unlockUserRequest request)
        {
            return base.Channel.unlockUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.renameRoleResponse> renameRoleAsync(OMASServiceReference.renameRoleRequest request)
        {
            return base.Channel.renameRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.getRoleDetailsResponse> getRoleDetailsAsync(OMASServiceReference.getRoleDetailsRequest request)
        {
            return base.Channel.getRoleDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OMASServiceReference.setUserDepotResponse> setUserDepotAsync(OMASServiceReference.setUserDepotRequest request)
        {
            return base.Channel.setUserDepotAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OMASWebSvcs))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OMASWebSvcs))
            {
                return new System.ServiceModel.EndpointAddress("https://services.omnitracs.com/omasWebWS/services/OMASWebSvcs");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OMASWebSvcsClient.GetBindingForEndpoint(EndpointConfiguration.OMASWebSvcs);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OMASWebSvcsClient.GetEndpointAddress(EndpointConfiguration.OMASWebSvcs);
        }
        
        public enum EndpointConfiguration
        {
            
            OMASWebSvcs,
        }
    }
}
