
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('ARMSTRONG OPERATING, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('BARANKO BROS., INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('BJ SERVICES, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('BRACE INTEGRATED');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('BRINK CONSTRUCTORS, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('BRUIN E&P OPERATING');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('CARSTENSEN CONTRACTING, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('COIL TUBING PARTNERS');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('CONOCOPHILLIPS COMPANY');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('CONTINENTAL RESOURCES, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('CUDD ENERGY SERVICES');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('DENBURY ONSHORE, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('DGI MENARD');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('EQUINOR ');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('GOTTA GO TRUCK''N');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('HALLIBURTON');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('HAMS WELL SERVICE');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('HUNT OIL COMPANY');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('IRON OIL ');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('KRAKEN OPERATING, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('LIBERTY OILFIELD SERVICES');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('LIBERTY RESOURCES MANAGEMENT COMPANY, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('LIME ROCK RESOURCES');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('MARATHON OIL COMPANY ');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('MARTIN CONSTRUCTION');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('MCKENZIE CO ROAD DEPT');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('NEWFIELD EXPLORATION COMPANY');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('NOAH ENERGY, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('NORTH DAKOTA LNG, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('NORTHWINDS OF WYOMING');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('OASIS PETROLEUM, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('PATRIOT WELL SOLUTIONS, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('PERFX WIRELINE SERVICES, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('PETRO HARVESTER OPERATING');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('PETRO HARVESTOR OPERATING COMPANY');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('PETRO-HUNT, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('QEP ENERGY COMPANY');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('ROLFSON OIL, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('SAMIA TRANSPORT');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('SCHLUMBERGER TECH CORP');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('SLAWSON EXPLORATION COMPANY, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('SLOAN GROUT');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('TEK ENERGY SERVICES, LLC');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('WHITING OIL & GAS');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('WISE SERVICES, INC.');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('WPX ENERGY');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('XTO ENERGY');
INSERT INTO `ro_ticketing`.`customer` (`Name`) VALUES ('ZAVANNA, LLC');
