truncate table ro_ticketing.PRODUCT;

INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (2,'Clear Diesel #1',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (3,'Clear Diesel #2',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (4,'Clear Winter Blend Diesel',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (5,'Containment Rental',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (6,'Delivery Fee',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (7,'Demobilization Fee',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (8,'Demurrage Fee',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (9,'Diesel Exhaust Fluid',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (10,'Disposal Fee',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (11,'Dyed Diesel #1',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (12,'Dyed Diesel #2',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (13,'Dyed Winter Blend Diesel',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (14,'Employee Travel Time',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (15,'Fabrication Package 1',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (16,'Fabrication Package 2',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (17,'Fabrication Package 3',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (18,'Fabrication Package 4',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (19,'Frac Truck and Crew',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (20,'Frac Truck and Driver',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (21,'Fuel Tech',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (22,'Gasoline',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (23,'Mobilization Fee',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (24,'Mud Drill Pro + Concentrate',1,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (25,'On-Site Crew Vehicle',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (26,'On-Site DEF Vehicle',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (27,'OSR',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (28,'Parts Package 1',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (29,'Parts Package 2',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (30,'Parts Package 3',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (31,'Parts Package 4',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (32,'Per Diem',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (33,'Permit',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (34,'Safety Meeting Time',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (35,'Suck Out Fee',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (36,'Surcharge',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (37,'Tank Delivery',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (38,'Tank Rental',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (39,'Tank/Mechanic Labor',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (40,'Tote Deposit',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (41,'Transport Truck',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (42,'Wet Hosing',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (43,'Surcharge Credit',2,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (44,'travel time',3,1);
INSERT INTO ro_ticketing.PRODUCT (id,name,unitId,isIncludedInReport) VALUE (45,'Transport',3,1);