use ro_ticketing;

INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'AMOR JOSEPH','4415','432-254-9630','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'ANDERSON LOUIS','8044','402-301-3421','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BALE ALLEN','2587','253-878-2593','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BANCROFT MATTHEW','3072','616-240-7393','FRAC DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BELTRAN VICTOR','0607','956-6756','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BERNARD GREGORY','9454','(901)443-7714','FRAC ', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BETZ CHAD','0835','225-362-0420','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BLACKMAN DAVID','3562','601-826-6259','FRAC DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BLAN ANTHONY','3841','916-504-6308','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BLANCO CARLOS','9734','915-731-0055','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BOHN JUSTIN','8973','605-499-8546','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BREWER TOM','2930','406-480-7455','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BUCHLI ALEX','8557','(720)607-5745','Tickets until the phones get fixed', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BULL GEORGE','1584','432-924-8190','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BURR GEORGE ','1481','7606865156','FRAC ', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BURR GEORGE','1481','760-686-5156','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BUSHO CHRIS','5594','850-313-0247','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'BUSTOS MARK','8909','806-274-1922','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'CARR JOHNNY','5059','239-834-4502','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'CARTER JEFFERY','4614','704-299-8899','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'CORONADO STEVEN','2228','575-637-2599','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'COUCH GREGORY','3388','720-330-7614','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'CRAVEN ROBERT','8954','727-389-6609','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'CUNNINGHAM KEITH','7412','859-230-1086','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'CURRIER JOHN','6445','970-317-7550','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'DUCHARM PATRICK','4059','630-618-6169','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'DUKES ANTHONY','0710','360-843-0726','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'FARMER RONALD','9106','307-343-2275','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'GLASS CONWAY','1658','707-391-1614','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'GORDON ALVIN','7612','903-244-0080','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'GROVE JON','2552','541-406-9904','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'GUENTENSBERGER RONALD','4391','989-513-2813','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'HAGGARD JAMES','6543','580-821-6028','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'HAMLET KEE','4548','(720)692-1434','FRAC ', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'HARRIS JOHN','1776','719-499-5309','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'HOUSTON ANTON','4179','864-602-0110','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'HULL KENT','8462','980-258-3663','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'JOHNSON AUSTIN','8704','208-818-4220','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'JOHNSON DANIEL','3962','602-793-7386','FRAC DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'JOHNSON GEORGE','4296','432-553-8590','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'JONES DANTAVIS','0764','901-846-4838','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'JONES KEITH','8957','850-963-6622','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'KLIEN HANK','3722','517-202-2591','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'KNOTT KOSE','0958','701-629-5208','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'KRUA JEFF','3390','617-275-6212','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'LANGSDORF ZACH','6161','3038859966','FRAC ', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'LUCHENBURG GLENN','4639','432-209-5135','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'MAKHLOUFI YAZID','4567','816-345-5273','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'MAZERIEGOS HERNAN','6902','281-435-7457','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'MCGUIRE ADRIAN','0077','432-803-3989','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'N/A','0000','','', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'NA','NA','NA','NA', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'NELSON CLAYTON','6300','(701)330-5714','FRAC ', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'NORRIS THOMAS','2013','432-234-1088','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'OAKLEAF STEVEN','7528','660-654-1081','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'OAKLEAF STEVEN','7528','6606541081','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'OHRT RODNEY','9880','(262)422-5688','FRAC ', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'PENDLETON JEFFERY','9224','5627067655','FRAC ', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'PHILEMON RICHARD','5726','540-940-4830','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'POLK MARCUS','6493','432-559-3806','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'PONTO RANDY','1567','701-770-8913','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'POWER PADRAIC','2310','701-421-2085','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'PRINCE MICHAEL','1648','701-340-6326','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'RACANELLI JONATHEN','1609','720-333-8334','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'REYES JOSE','9473','432-272-9220','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'REYNOLDS MICHAEL','5270','303-877-2990','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'ROGERS CARVETTE','7373','281-964-5395','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'ROMERO DAVID','1990','361-676-9338','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SALGADO KEVIN','5898','563-568-1115','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SAMPSON JAMAL','9529','832-290-8370','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SCHULTZ STEVEN','6858','517-582-4977','NON CDL DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SEGURA OLGA','4365','575-703-7641','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SHOLTEY SCOTT','3310','810-614-5994','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SLAUGHTER FRANK','0864','541-670-5490','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SLIDER CARLOS','6396','817-818-7383','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SLIDER CARLOS','6396','817-818-7383','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'STEVEN SCHULTZ','6858','517-582-4977','FUEL TRUCK DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'STEVENS JOSEPH','4250','505-620-1051','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'SYMONDS MICHAEL','5288','915-999-4045','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'TEST DRIVER','0000','','', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'TEST','9876','123456789','', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'THOMPKINS CHARLES','1650','562-314-9925','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'THOMPSON LATRISTEN','5173','903-285-9317','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'TIRADO JASON','9260','432-202-2615','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'TOOLIE MISCHEALINDA','4538','901-570-8452','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'TRUSS ARKILL','4981','601-941-3661','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'TRUSS JAVIER','7415','(601)201-5574','FRAC DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'USHER FRED','8043','602-339-0286','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'VILLARROEL JAIME','5507','571-286-1375','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'WALKER VICTOR','0166','432-556-5385','TRANSPORT', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'WANNER ROBERT','3853','315-730-4952','FRAC DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'WILLIAMS ANDREW','1764','715-741-0844','', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'WILLIAMS IVORRI(GIO)','2666','786-606-0936','FRAC DRIVER', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'WILSON LORENZO','7162','561-853-8769','FRAC', 1, 0 );
INSERT INTO `ro_ticketing`.`driver` (`Name`, `Code`, `Phone`, `Position`, `IsEnabled`, `IsDeleted`) VALUES  ( 'WOLLGAST CHRISTOPHER','4502','406-241-3575','TRANSPORT', 1, 0 );