//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMMWebSvcsReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exception.sharedws")]
    public partial class WSException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.qtracswebws")]
    public partial class MacroItem
    {
        
        private int columnField;
        
        private string dictNameField;
        
        private string dictTagField;
        
        private string groupNameField;
        
        private int groupNumField;
        
        private string groupTagField;
        
        private int lengthField;
        
        private bool requiredField;
        
        private int rowField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string dictName
        {
            get
            {
                return this.dictNameField;
            }
            set
            {
                this.dictNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string dictTag
        {
            get
            {
                return this.dictTagField;
            }
            set
            {
                this.dictTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string groupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int groupNum
        {
            get
            {
                return this.groupNumField;
            }
            set
            {
                this.groupNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string groupTag
        {
            get
            {
                return this.groupTagField;
            }
            set
            {
                this.groupTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool required
        {
            get
            {
                return this.requiredField;
            }
            set
            {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.qtracswebws")]
    public partial class MacroDefinition
    {
        
        private int assocRtnMacField;
        
        private string definitionStatusField;
        
        private string descriptionField;
        
        private string directionField;
        
        private MacroItem[] macroItemListField;
        
        private bool msgSuprField;
        
        private string nameField;
        
        private int numberField;
        
        private bool routeCoverageField;
        
        private string rtnMacCoverageField;
        
        private int usageField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int assocRtnMac
        {
            get
            {
                return this.assocRtnMacField;
            }
            set
            {
                this.assocRtnMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string definitionStatus
        {
            get
            {
                return this.definitionStatusField;
            }
            set
            {
                this.definitionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MacroItem[] macroItemList
        {
            get
            {
                return this.macroItemListField;
            }
            set
            {
                this.macroItemListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool msgSupr
        {
            get
            {
                return this.msgSuprField;
            }
            set
            {
                this.msgSuprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool routeCoverage
        {
            get
            {
                return this.routeCoverageField;
            }
            set
            {
                this.routeCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string rtnMacCoverage
        {
            get
            {
                return this.rtnMacCoverageField;
            }
            set
            {
                this.rtnMacCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int usage
        {
            get
            {
                return this.usageField;
            }
            set
            {
                this.usageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://websvcs.qtracswebws", ConfigurationName="TMMWebSvcsReference.TMMWebSvcs")]
    public interface TMMWebSvcs
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.createMacroResponse> createMacroAsync(TMMWebSvcsReference.createMacroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.deleteMacroResponse> deleteMacroAsync(TMMWebSvcsReference.deleteMacroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.getMacroListResponse> getMacroListAsync(TMMWebSvcsReference.getMacroListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.createDictionaryEntryResponse> createDictionaryEntryAsync(TMMWebSvcsReference.createDictionaryEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.sendBinaryMessageResponse> sendBinaryMessageAsync(TMMWebSvcsReference.sendBinaryMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.deleteDictionaryEntryResponse> deleteDictionaryEntryAsync(TMMWebSvcsReference.deleteDictionaryEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.getMacroResponse> getMacroAsync(TMMWebSvcsReference.getMacroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.ccReturnMessageResponse> ccReturnMessageAsync(TMMWebSvcsReference.ccReturnMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.getDictionaryEntryResponse> getDictionaryEntryAsync(TMMWebSvcsReference.getDictionaryEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.markMessageSeenResponse> markMessageSeenAsync(TMMWebSvcsReference.markMessageSeenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.getMacroExResponse> getMacroExAsync(TMMWebSvcsReference.getMacroExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TMMWebSvcsReference.WSException), Action="", Name="WSException", Namespace="http://exception.sharedws")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TMMWebSvcsReference.sendTextMessageResponse> sendTextMessageAsync(TMMWebSvcsReference.sendTextMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createMacro", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class createMacroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TMMWebSvcsReference.MacroDefinition macro;
        
        public createMacroRequest()
        {
        }
        
        public createMacroRequest(TMMWebSvcsReference.MacroDefinition macro)
        {
            this.macro = macro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createMacroResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class createMacroResponse
    {
        
        public createMacroResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteMacro", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class deleteMacroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string direction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number;
        
        public deleteMacroRequest()
        {
        }
        
        public deleteMacroRequest(string direction, int number)
        {
            this.direction = direction;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteMacroResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class deleteMacroResponse
    {
        
        public deleteMacroResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMacroList", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getMacroListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string direction;
        
        public getMacroListRequest()
        {
        }
        
        public getMacroListRequest(string direction)
        {
            this.direction = direction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMacroListResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getMacroListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TMMWebSvcsReference.MacroDefinition[] getMacroListReturn;
        
        public getMacroListResponse()
        {
        }
        
        public getMacroListResponse(TMMWebSvcsReference.MacroDefinition[] getMacroListReturn)
        {
            this.getMacroListReturn = getMacroListReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.qtracswebws")]
    public partial class DictionaryEntry
    {
        
        private int assocRtnMacField;
        
        private string descriptionField;
        
        private string dictionaryTypeField;
        
        private string directionField;
        
        private string entryTypeField;
        
        private string enumerationsField;
        
        private int mobileDataTypeField;
        
        private int mobileLengthField;
        
        private bool inUseField;
        
        private string nameField;
        
        private string xmlTagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int assocRtnMac
        {
            get
            {
                return this.assocRtnMacField;
            }
            set
            {
                this.assocRtnMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string dictionaryType
        {
            get
            {
                return this.dictionaryTypeField;
            }
            set
            {
                this.dictionaryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string entryType
        {
            get
            {
                return this.entryTypeField;
            }
            set
            {
                this.entryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string enumerations
        {
            get
            {
                return this.enumerationsField;
            }
            set
            {
                this.enumerationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int mobileDataType
        {
            get
            {
                return this.mobileDataTypeField;
            }
            set
            {
                this.mobileDataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int mobileLength
        {
            get
            {
                return this.mobileLengthField;
            }
            set
            {
                this.mobileLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool inUse
        {
            get
            {
                return this.inUseField;
            }
            set
            {
                this.inUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string xmlTag
        {
            get
            {
                return this.xmlTagField;
            }
            set
            {
                this.xmlTagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDictionaryEntry", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class createDictionaryEntryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TMMWebSvcsReference.DictionaryEntry entry;
        
        public createDictionaryEntryRequest()
        {
        }
        
        public createDictionaryEntryRequest(TMMWebSvcsReference.DictionaryEntry entry)
        {
            this.entry = entry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDictionaryEntryResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class createDictionaryEntryResponse
    {
        
        public createDictionaryEntryResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBinaryMessage", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class sendBinaryMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string addressees;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool returnReceipt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int virtualChannel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] body;
        
        public sendBinaryMessageRequest()
        {
        }
        
        public sendBinaryMessageRequest(string addressees, bool returnReceipt, int priority, int virtualChannel, byte[] body)
        {
            this.addressees = addressees;
            this.returnReceipt = returnReceipt;
            this.priority = priority;
            this.virtualChannel = virtualChannel;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBinaryMessageResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class sendBinaryMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sendBinaryMessageReturn;
        
        public sendBinaryMessageResponse()
        {
        }
        
        public sendBinaryMessageResponse(int sendBinaryMessageReturn)
        {
            this.sendBinaryMessageReturn = sendBinaryMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDictionaryEntry", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class deleteDictionaryEntryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string xmlTag;
        
        public deleteDictionaryEntryRequest()
        {
        }
        
        public deleteDictionaryEntryRequest(string xmlTag)
        {
            this.xmlTag = xmlTag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDictionaryEntryResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class deleteDictionaryEntryResponse
    {
        
        public deleteDictionaryEntryResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMacro", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getMacroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string direction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number;
        
        public getMacroRequest()
        {
        }
        
        public getMacroRequest(string direction, int number)
        {
            this.direction = direction;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMacroResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getMacroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TMMWebSvcsReference.MacroDefinition getMacroReturn;
        
        public getMacroResponse()
        {
        }
        
        public getMacroResponse(TMMWebSvcsReference.MacroDefinition getMacroReturn)
        {
            this.getMacroReturn = getMacroReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ccReturnMessage", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class ccReturnMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int inGMH;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ccName;
        
        public ccReturnMessageRequest()
        {
        }
        
        public ccReturnMessageRequest(int inGMH, string ccName)
        {
            this.inGMH = inGMH;
            this.ccName = ccName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ccReturnMessageResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class ccReturnMessageResponse
    {
        
        public ccReturnMessageResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDictionaryEntry", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getDictionaryEntryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string xmlTag;
        
        public getDictionaryEntryRequest()
        {
        }
        
        public getDictionaryEntryRequest(string xmlTag)
        {
            this.xmlTag = xmlTag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDictionaryEntryResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getDictionaryEntryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TMMWebSvcsReference.DictionaryEntry getDictionaryEntryReturn;
        
        public getDictionaryEntryResponse()
        {
        }
        
        public getDictionaryEntryResponse(TMMWebSvcsReference.DictionaryEntry getDictionaryEntryReturn)
        {
            this.getDictionaryEntryReturn = getDictionaryEntryReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="markMessageSeen", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class markMessageSeenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int inGMH;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string markAllSeen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userOrCvg;
        
        public markMessageSeenRequest()
        {
        }
        
        public markMessageSeenRequest(int inGMH, string markAllSeen, string userOrCvg)
        {
            this.inGMH = inGMH;
            this.markAllSeen = markAllSeen;
            this.userOrCvg = userOrCvg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="markMessageSeenResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class markMessageSeenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string markMessageSeenReturn;
        
        public markMessageSeenResponse()
        {
        }
        
        public markMessageSeenResponse(string markMessageSeenReturn)
        {
            this.markMessageSeenReturn = markMessageSeenReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.qtracswebws")]
    public partial class MacroDefinitionEx
    {
        
        private MacroItemEx[] macroItemListField;
        
        private int assocRtnMacField;
        
        private string definitionStatusField;
        
        private string descriptionField;
        
        private string directionField;
        
        private bool msgSuprField;
        
        private string nameField;
        
        private int numberField;
        
        private bool routeCoverageField;
        
        private string rtnMacCoverageField;
        
        private int usageField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MacroItemEx[] macroItemList
        {
            get
            {
                return this.macroItemListField;
            }
            set
            {
                this.macroItemListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int assocRtnMac
        {
            get
            {
                return this.assocRtnMacField;
            }
            set
            {
                this.assocRtnMacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string definitionStatus
        {
            get
            {
                return this.definitionStatusField;
            }
            set
            {
                this.definitionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool msgSupr
        {
            get
            {
                return this.msgSuprField;
            }
            set
            {
                this.msgSuprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool routeCoverage
        {
            get
            {
                return this.routeCoverageField;
            }
            set
            {
                this.routeCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string rtnMacCoverage
        {
            get
            {
                return this.rtnMacCoverageField;
            }
            set
            {
                this.rtnMacCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int usage
        {
            get
            {
                return this.usageField;
            }
            set
            {
                this.usageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datatype.qtracswebws")]
    public partial class MacroItemEx
    {
        
        private string descriptionField;
        
        private string dictionaryTypeField;
        
        private string directionAllowedField;
        
        private string entryTypeField;
        
        private string enumerationsField;
        
        private bool inUseField;
        
        private int mobileDataTypeField;
        
        private int mobileLengthField;
        
        private int columnField;
        
        private string dictNameField;
        
        private string dictTagField;
        
        private string groupNameField;
        
        private int groupNumField;
        
        private string groupTagField;
        
        private int lengthField;
        
        private bool requiredField;
        
        private int rowField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string dictionaryType
        {
            get
            {
                return this.dictionaryTypeField;
            }
            set
            {
                this.dictionaryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string directionAllowed
        {
            get
            {
                return this.directionAllowedField;
            }
            set
            {
                this.directionAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string entryType
        {
            get
            {
                return this.entryTypeField;
            }
            set
            {
                this.entryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string enumerations
        {
            get
            {
                return this.enumerationsField;
            }
            set
            {
                this.enumerationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool inUse
        {
            get
            {
                return this.inUseField;
            }
            set
            {
                this.inUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int mobileDataType
        {
            get
            {
                return this.mobileDataTypeField;
            }
            set
            {
                this.mobileDataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int mobileLength
        {
            get
            {
                return this.mobileLengthField;
            }
            set
            {
                this.mobileLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string dictName
        {
            get
            {
                return this.dictNameField;
            }
            set
            {
                this.dictNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string dictTag
        {
            get
            {
                return this.dictTagField;
            }
            set
            {
                this.dictTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string groupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int groupNum
        {
            get
            {
                return this.groupNumField;
            }
            set
            {
                this.groupNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string groupTag
        {
            get
            {
                return this.groupTagField;
            }
            set
            {
                this.groupTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public bool required
        {
            get
            {
                return this.requiredField;
            }
            set
            {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMacroEx", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getMacroExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string direction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number;
        
        public getMacroExRequest()
        {
        }
        
        public getMacroExRequest(string direction, int number)
        {
            this.direction = direction;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMacroExResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class getMacroExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TMMWebSvcsReference.MacroDefinitionEx getMacroExReturn;
        
        public getMacroExResponse()
        {
        }
        
        public getMacroExResponse(TMMWebSvcsReference.MacroDefinitionEx getMacroExReturn)
        {
            this.getMacroExReturn = getMacroExReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendTextMessage", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class sendTextMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string addressees;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string replyTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool returnReceipt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int macro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string body;
        
        public sendTextMessageRequest()
        {
        }
        
        public sendTextMessageRequest(string sender, string addressees, string replyTo, bool returnReceipt, int priority, int macro, string body)
        {
            this.sender = sender;
            this.addressees = addressees;
            this.replyTo = replyTo;
            this.returnReceipt = returnReceipt;
            this.priority = priority;
            this.macro = macro;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendTextMessageResponse", WrapperNamespace="http://websvcs.qtracswebws", IsWrapped=true)]
    public partial class sendTextMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://websvcs.qtracswebws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sendTextMessageReturn;
        
        public sendTextMessageResponse()
        {
        }
        
        public sendTextMessageResponse(int sendTextMessageReturn)
        {
            this.sendTextMessageReturn = sendTextMessageReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface TMMWebSvcsChannel : TMMWebSvcsReference.TMMWebSvcs, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class TMMWebSvcsClient : System.ServiceModel.ClientBase<TMMWebSvcsReference.TMMWebSvcs>, TMMWebSvcsReference.TMMWebSvcs
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TMMWebSvcsClient() : 
                base(TMMWebSvcsClient.GetDefaultBinding(), TMMWebSvcsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TMMWebSvcs.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TMMWebSvcsClient(EndpointConfiguration endpointConfiguration) : 
                base(TMMWebSvcsClient.GetBindingForEndpoint(endpointConfiguration), TMMWebSvcsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TMMWebSvcsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TMMWebSvcsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TMMWebSvcsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TMMWebSvcsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TMMWebSvcsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.createMacroResponse> createMacroAsync(TMMWebSvcsReference.createMacroRequest request)
        {
            return base.Channel.createMacroAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.deleteMacroResponse> deleteMacroAsync(TMMWebSvcsReference.deleteMacroRequest request)
        {
            return base.Channel.deleteMacroAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.getMacroListResponse> getMacroListAsync(TMMWebSvcsReference.getMacroListRequest request)
        {
            return base.Channel.getMacroListAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.createDictionaryEntryResponse> createDictionaryEntryAsync(TMMWebSvcsReference.createDictionaryEntryRequest request)
        {
            return base.Channel.createDictionaryEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.sendBinaryMessageResponse> sendBinaryMessageAsync(TMMWebSvcsReference.sendBinaryMessageRequest request)
        {
            return base.Channel.sendBinaryMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.deleteDictionaryEntryResponse> deleteDictionaryEntryAsync(TMMWebSvcsReference.deleteDictionaryEntryRequest request)
        {
            return base.Channel.deleteDictionaryEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.getMacroResponse> getMacroAsync(TMMWebSvcsReference.getMacroRequest request)
        {
            return base.Channel.getMacroAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.ccReturnMessageResponse> ccReturnMessageAsync(TMMWebSvcsReference.ccReturnMessageRequest request)
        {
            return base.Channel.ccReturnMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.getDictionaryEntryResponse> getDictionaryEntryAsync(TMMWebSvcsReference.getDictionaryEntryRequest request)
        {
            return base.Channel.getDictionaryEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.markMessageSeenResponse> markMessageSeenAsync(TMMWebSvcsReference.markMessageSeenRequest request)
        {
            return base.Channel.markMessageSeenAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.getMacroExResponse> getMacroExAsync(TMMWebSvcsReference.getMacroExRequest request)
        {
            return base.Channel.getMacroExAsync(request);
        }
        
        public System.Threading.Tasks.Task<TMMWebSvcsReference.sendTextMessageResponse> sendTextMessageAsync(TMMWebSvcsReference.sendTextMessageRequest request)
        {
            return base.Channel.sendTextMessageAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TMMWebSvcs))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TMMWebSvcs))
            {
                return new System.ServiceModel.EndpointAddress("https://services.omnitracs.com/qtracsWebWS/services/TMMWebSvcs");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TMMWebSvcsClient.GetBindingForEndpoint(EndpointConfiguration.TMMWebSvcs);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TMMWebSvcsClient.GetEndpointAddress(EndpointConfiguration.TMMWebSvcs);
        }
        
        public enum EndpointConfiguration
        {
            
            TMMWebSvcs,
        }
    }
}
